# Generated by Django 5.1.6 on 2025-02-12 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(related_name='workers', to=settings.AUTH_USER_MODEL),
        ),
    ]
